# SwiftLint Configuration for AmakaFlow iOS

# Rules to disable
disabled_rules:
  - trailing_whitespace  # Xcode handles this
  - line_length          # Allow longer lines for SwiftUI

# Rules to opt-in
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicit_return
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Paths to include/exclude
included:
  - AmakaFlow
  - AmakaFlowCompanion

excluded:
  - Pods
  - .build
  - DerivedData
  - AmakaFlowCompanion/AmakaFlowCompanion.xcodeproj
  - AmakaFlowCompanion/AmakaFlowCompanionTests
  - AmakaFlowCompanion/AmakaFlowCompanionUITests

# Custom rule configurations
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 100
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
reporter: "xcode"

